name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
      - dev-release  # Ensures the workflow runs on both branches
  pull_request:
    branches:
      - main
      - dev-release

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Use your required Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev,docs]"

      - name: Generate API Documentation
        run: |
          cd docs
          sphinx-apidoc -o docs/source/ ../HIL/  # Generate documentation from ../HIL/
          # Adjust paths as necessary

      - name: Build Documentation
        run: |
          cd docs
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html  # Ensure this matches your Sphinx output directory
